export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAILED = "PRODUCT_FETCH_FAILED";
export const QUANTITY_PLUS = "QUANTITY_PLUS";
